// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxL6FLhbF74FHr5CV-gEc_Resc63PKhg',
    appId: '1:64160194781:web:1d7062ab18312367613b34',
    messagingSenderId: '64160194781',
    projectId: 'gemo-lab3',
    authDomain: 'gemo-lab3.firebaseapp.com',
    storageBucket: 'gemo-lab3.appspot.com',
    measurementId: 'G-NWBKHB6MWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5DgnCBG1eD8Ysg3QrXP2HV8QK6QaIbSQ',
    appId: '1:64160194781:android:3ac13a1364a06b4f613b34',
    messagingSenderId: '64160194781',
    projectId: 'gemo-lab3',
    storageBucket: 'gemo-lab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBos40EZ3Jzw4lZzP0JMsXUHyR0NfmKDTY',
    appId: '1:64160194781:ios:c327343194c1e9e2613b34',
    messagingSenderId: '64160194781',
    projectId: 'gemo-lab3',
    storageBucket: 'gemo-lab3.appspot.com',
    iosClientId: '64160194781-p8tvgbjcr3b056uheltdeku5oa3avlah.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBos40EZ3Jzw4lZzP0JMsXUHyR0NfmKDTY',
    appId: '1:64160194781:ios:c327343194c1e9e2613b34',
    messagingSenderId: '64160194781',
    projectId: 'gemo-lab3',
    storageBucket: 'gemo-lab3.appspot.com',
    iosClientId: '64160194781-p8tvgbjcr3b056uheltdeku5oa3avlah.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShop',
  );
}
